language: cpp
sudo: false

os:
  - linux
  - osx

compiler:
  - clang

install:
  - ./src/third_party/gyp/gyp -f make --depth . --generator-output build src/fontdiff/fontdiff.gyp
  - make --directory build

script: true
